### ISSUE TITLE
Get underlying token prices for the pool

### ISSUE THREAD

**Issue by rakpawel** [curvefi/curve-js#102]
Hello,

I'm using this library to fetch data about current token balances in various pools. I'd like to access also underlying token prices as I saw it's available in the API under endpoint:
`GET /api/getPools/<blockchainId>/<registryId>`

Is there a way to access `poolData[x].coins[x].usdPrice` from this SDK? 
Looks like everything else is available under `pool.stats` field.

**Comment by Macket** [comment]
Try this. I should make this method public

```js
(async () => {
    await curve.init('JsonRpc', { url: ETH_RPC }, { gasPrice: 0 });
    
    const pool = curve.getPool('usdp');
    // @ts-ignore
    console.log(await pool._underlyingPrices());
}()
```
