### ISSUE TITLE
Different values for arbitrum CRV rewards on frontend vs. this app

### ISSUE THREAD

**Issue by riordant** [curvefi/curve-js#117]
```
        await curve.init('JsonRpc', { url: ARCHIVENODE_ARB }, { gasPrice: 0, maxFeePerGas: 0, maxPriorityFeePerGas: 0, chainId: 42161 });
        const _2pool = curve.getPool('2pool');
        const Rewards = await _2pool.stats.tokenApy();
        console.log(Rewards);
```

Returns:
`[ '2.1049', '5.2624' ]`

ie. CRV rewards of ~2.1%

CRV rewards at https://arbitrum.curve.fi:
![image](https://user-images.githubusercontent.com/6988731/204092270-3f965e8a-e056-4024-9c8a-a2c8e2d1fc63.png)

ie. CRV rewards of 1.37%

**Comment by Macket** [comment]
curve-js gives correct values (obtained from https://api.curve.fi/api/getPools/arbitrum/main). Old UI didn't update this part. Don't rely on it.
