### ISSUE TITLE
API doesn't fetch swap route and pools correctly.

### ISSUE THREAD

**Issue by AtosDev** [curvefi/curve-js#131]
1.When I call getFactoryPoolList and getCryptoFactoryPoolList functions, they return empty arrays in Polygon network.
2.When I call getBestRouteAndOutput function, it displays an error like that:
**Coin with address 'AAA' is not available**
But I can swap this token on curve.fi site.

**Comment by Macket** [comment]
I think you should call this first

```js
await curve.fetchFactoryPools();
await curve.fetchCryptoFactoryPools();
```

**Comment by AtosDev** [comment]
Hi Macket.
It works for me. Thx
