### ISSUE TITLE
Testnet mumbai issue

### ISSUE THREAD

**Issue by vaske** [curvefi/curve-js#147]
Hi all, I'm using your SDK to obtain SWAP details, and so far if I use it over mainnet polygon it works fine, but with testnet mumbai I have issues like 

```
Error: Coin with address '0xa6fa4fb5f76172d178d61b04b0ecd319c5d1c0aa' is not available
```
for WETH on mumbai for example

is it supported over testnet or I'm doing something wrong here?

**Comment by Macket** [comment]
This is because there is no any curve pool on mumbai testnet. SDK says that some coin is not available if it's not present in pools. Use local fork or mainnet for Curve, please.
