### ISSUE TITLE
getBestPoolAndOutput returns not pool address

### ISSUE THREAD

**Issue by vlad3k** [curvefi/curve-js#21]
USDC -> WETH
curve.getBestPoolAndOutput('0x2791bca1f2de4661ed88a30c99a7a9449aa84174', '0x7ceb23fd6bc0add59e62ac25578270cff1b9f619', '1.954569')

return poolAddress '0x0000000000000000000000000000000000000000'

**Comment by Macket** [comment]
Hi! The lib can't route such multipool swaps now. But this will be possible very soon

**Comment by Macket** [comment]
Hi! Use `curve.getBestRouteAndOutput` instead

More info: https://github.com/curvefi/curve-js#router-exchange
