### ISSUE TITLE
Curvejs Performance: (Router swap)

### ISSUE THREAD

**Issue by amytsang** [curvefi/curve-js#312]
Source code: https://github.com/curvefi/curve-js/blob/master/src/router.ts

Router performance profile is in the following screenshot (in the comments).

Priority topic, since router is the landing page and needs to be as fast as possible.

Solutions involve optimising the router.js code.

**Comment by amytsang** [comment]
![Image](https://github.com/curvefi/curve-js/assets/6961602/ba3fea26-5f29-4f2c-ad57-c95908bba5f3)

For every router swap, I called the following 3 functions: (one of these functions is making massive amounts of calls, which degrades UI performance to the point it is not usable. Need to figure out a way to move these away from the main thread.

```
curve.router.getBestRouteAndOutput(fromAddress, toAddress, fromAmount),
curve.router.expected(fromAddress, toAddress, fromAmount),
curve.router.priceImpact(fromAddress, toAddress, fromAmount),
```

**Comment by bout3fiddy** [comment]
For reference,

1. getBestRouteAndOutput is the main routing logic (uses breadth first search), returns an array of pools through with a swap should go through to go from input token to output token specified by the user.
2. expect gets the expected output from the swap by calling get_dy, or get_dy_underlying etc. of each individual pool in the calculated route.
3. price impact checks the difference between expected output calculated in step 2 versus the same for a very very small amount.
